import Head from 'next/head'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>Lets Build hulu</h1>
    {/* header */}
    {/* navbar */}
    {/* results */}
      
    </div>
  )
}
